# Generated by Django 5.0.6 on 2024-05-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_grupo', models.IntegerField()),
                ('limite_estudiantes', models.IntegerField()),
                ('tipo_grupo', models.CharField(choices=[('teoria', 'Teoria'), ('practica', 'Practica')], max_length=10)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Permutas.asignatura')),
                ('estudiante', models.ManyToManyField(to='Permutas.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Permuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permuta_estudiante1', to='Permutas.estudiante')),
                ('estudiante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permuta_estudiante2', to='Permutas.estudiante')),
                ('grupo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permuta_grupo1', to='Permutas.grupo')),
                ('grupo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permuta_grupo2', to='Permutas.grupo')),
            ],
        ),
    ]
